# **Numpy**

In [1]:
import numpy as np

## Ndaary

- multi-dimensional array object
- consist of 2 parts:
    * actual data
    * some meta data
- 0 indexed
- each element in ndarray is an object of data-type object called *dtype*
- An item extracted from ndarray, is represented by a Python object of an array scalar type

---

## Creating a Numpy array

### **single dimensional array** 

> `np.array([a,b,c,d,...])`

In [6]:
a = np.array([1,2,3])
print(a)

[1 2 3]


### **multi dimensional array**

> `np.array([[a,b,c,...], [x,y,...], ...])`

> Number of elements in `[ ]` = **number of columns**

> `[ ]` represents a row

> Number of [ ] = **number of rows**

In [10]:
b = np.array([[1,2], [3,4]])
print(b)

[[1 2]
 [3 4]]


> array of numbers of a specified range

In [13]:
arr1 = np.arange(10, 50)
print(arr1) # prints form 10 to 50, excluding 50

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


> array of zeroes

In [15]:
arr2 = np.zeros(5)
print(arr2)

[0. 0. 0. 0. 0.]


In [16]:
arr3 = np.zeros((5,5))
print(arr3)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


> Linearly spaced vector `np.linspace(start, stop, step)`

In [20]:
vector = np.linspace(0,20,5)
print(vector)

[ 0.  5. 10. 15. 20.]


> array form existing data type

> `np.asarray(a, dtype = None, order = None)`

In [22]:
x = [1,2,3]
c = np.asarray(x)
print(x)

[1, 2, 3]


> Re-shape array

In [51]:
arr4 = np.zeros(12)
arr41 = arr4.reshape((3,2,2))
print(arr41)

[[[0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]]]


In [52]:
np.reshape(arr4,(2,3,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [53]:
np.reshape(arr4,(2,2,3))

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

> Flatten an array

In [56]:
np.ravel(arr4)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

---

## Indexing a NumPy Array

- 0 indexing

In [58]:
arr5 = np.arange(2,20)
print(arr5[8])

10


- Slicing like python

In [69]:
arr6 = np.arange(20)
arr6

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [70]:
arr6[slice(1, 10, 2)]

array([1, 3, 5, 7, 9])

In [66]:
arr6[2:] # starting from index 2

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [72]:
arr6[:15] # till index 15

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [92]:
d = np.array([[1,2,3], [4,5,6], [7,8,9]])
d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [79]:
d[0:2, 0:2] # Slice the first two rows and the first two columns

array([[1, 2],
       [4, 5]])

In [80]:
d[:]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [83]:
d[1:]

array([[4, 5, 6],
       [7, 8, 9]])

In [88]:
d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [97]:
d[:2,:1]

array([[1],
       [4]])

> `d[slice range row : slice range col]`

---

## Numpy Array Attributes

In [102]:
d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [99]:
print(d.shape) # Returns a tuple consisting of array dimensions

(3, 3)


In [100]:
print(d.ndim) # Attribute returns the number of array dimensions

2


In [101]:
print(a.itemsize) # Returns the length of each element of array in bytes

4


In [108]:
y = np.ones([3,2], dtype = int)
y

array([[1, 1],
       [1, 1],
       [1, 1]])

---